name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Github Action Job"
          
        - name: List files
          run: ls

        - name: Read file
          shell: bash
          run: cat README.md 1> /dev/null 2> /dev/null


            