name: Matrix Workflow

on: workflow_dispatch

jobs:
    matrix_job:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                images: [hello, alpine]
        runs-on: ${{ matrix.images }}
        steps:
            - name: Get the Image
              run: echo docker run ${{ matrix.images }}