name: Generate ASCII Artwork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Github Action Job"

        - name: Check out
          uses: actions/checkout@v4.1.7
         
        - name: Install sowsay program
          run: |
            sudo apt-get install cowsay -y

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON" >> dragon.txt

        - name: Generate ASCII Artwork
          run: grep -i "dragon" dragon.txt

        - name: Read file
          shell: bash
          run: cat dragon.txt

        - name: List repo files
          run: ls -la 