name: Generate ASCII Artwork

on: push

jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My First Github Action Job"

        - name: Check out
          uses: actions/checkout@v4.1.7
         
        - name: Execute shell script
          run: |
            chmod +x ./ascii-script.sh
            ./ascii-script.sh